### SECRET PATH ANND AUTHN TOKEN FILE LOCATION GIVEN HERE
### AUTHN IS SIDECAR
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oc-test-app-api-sidecar
  name: oc-test-app-api-sidecar
  namespace: test-app-namespace-2
spec:
  selector:
    matchLabels:
      app: oc-test-app-api-sidecar
  replicas: 1
  template:
    metadata:
      labels:
        app: oc-test-app-api-sidecar
    spec:
      serviceAccountName: oc-test-app-sa2
      containers:
        - name: oc-test-app-api-sidecar
          image: harbor.swo.local/engin/test-app-api-sidecar:r
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: conjur-connect
          volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            reeadOnly: true
          env:
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
          - name: SECRET0_PATH
            value: /secrets/swo-uat/variable/secrets/connection_str
          - name: SECRET1_PATH
            value: /secrets/swo-uat/variable/secretsdev/app_user
          - name: SECRET2_PATH
            value: /secrets/swo-uat/variable/secretsdev/app_pass

        - image: harbor.swo.local/engin/conjur-authn-k8s-client:latest
          imagePullPolicy: Always
          name: authenticator
          env:
            - name: CONJUR_AUTHN_LOGIN
              value: host/conjur/authn-k8s/hub-swo-local-cluster/apps/oc-test-app-api-sidecar
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - mountPath: /run/conjur
              name: conjur-access-token
          resources:
            limits:
              cpu: "0.000019m"
              memory: "16Mi"
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory